services:
  db:
    image: postgres:16.3
    container_name: Foundation
    environment:
      POSTGRES_DB: newdatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raxon789
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
volumes:
  db-data: